import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true });
const p = await (await b.newContext({ viewport: { width: 1240, height: 900 } })).newPage();
p.on('pageerror', e => console.log('FEHLER', e.message.slice(0,200)));
await p.goto('http://localhost:8787/konsole');
await p.waitForTimeout(3500);
console.log('Karten:', await p.locator('.karte').count());
console.log('Ringe gefüllt:', await p.evaluate(() => document.getElementById('r-cpu').style.strokeDashoffset));
console.log('Zahlen:', await p.locator('.zahl-kachel .n').allInnerTexts());
console.log('Knöpfe:', await p.locator('button').allInnerTexts());
await p.screenshot({ path: '/tmp/konsole.png', fullPage: true });
await b.close();
